import { AppShell } from "./app-shell";
import { AlertTriangle, Network, ShieldCheck, Sparkles, Workflow } from "./icons";

const content: Record<string, { eyebrow: string; title: string; description: string; cards: [string,string,string][] }> = {
  wisdom: { eyebrow: "ORCHESTRATION PREVIEW", title: "Wisdom Mode", description: "A transparent chief-of-staff workflow for decomposition, routing, approvals, and synthesis. Scaffolded for Phase 3; no orchestration is claimed live.", cards: [["Objective map","Original goal, assumptions, and success criteria","PLANNED"],["Guide assignments","Specialist guides with disclosed provider routing","PLANNED"],["Final synthesis","Consensus, conflicts, evidence gaps, uncertainty","PLANNED"]] },
  compare: { eyebrow: "EVALUATION WORKSPACE", title: "Compare", description: "Side-by-side answers, criteria-weighted scorecards, contradictions, and evidence review. Council outputs will feed this in Phase 2.", cards: [["Comparison canvas","Side-by-side, stacked, and carousel views","SCAFFOLDED"],["Evidence inspection","Citation overlap and unsupported claim flags","PLANNED"],["Transparent scoring","Model judgments labeled as estimates","PLANNED"]] },
  guides: { eyebrow: "AGENT REGISTRY", title: "Knowledge Guides", description: "Configure specialist roles, providers, tools, memory, approval gates, and evaluation criteria.", cards: [["Research Guide","Source discovery and evidence inspection","INACTIVE"],["Technical Guide","Architecture and implementation review","INACTIVE"],["Verification Guide","Objective checks and uncertainty reporting","INACTIVE"]] },
  workflows: { eyebrow: "REUSABLE OPERATIONS", title: "Workflows", description: "Form-based plans with steps, dependencies, budget limits, retry rules, and approval gates.", cards: [["Research & verify","Discover, cross-check, synthesize","TEMPLATE"],["Council decision","Fan out, critique, find consensus","TEMPLATE"],["Build a feature","Plan, implement, test, approve","TEMPLATE"]] },
  files: { eyebrow: "AUTHORIZED ASSETS", title: "Files", description: "File validation and provider-scoped sharing will arrive in Phase 2. No filesystem access is exposed to the browser.", cards: [["Upload boundary","Validated file types and size limits","PLANNED"],["Provider disclosure","See which provider receives each asset","PLANNED"],["Retention controls","Export and deletion controls","PLANNED"]] },
  memory: { eyebrow: "CONTEXT CONTROL", title: "Memory", description: "Inspect, pin, correct, archive, export, and delete attributed context. Phase 1 project conversations are persisted locally.", cards: [["Conversation memory","Saved with project conversations","AVAILABLE"],["Guide memory","Specialist-scoped retained context","PLANNED"],["Organization knowledge","Attributed retrieval layer","PLANNED"]] },
  usage: { eyebrow: "COST & PERFORMANCE", title: "Usage", description: "No invented cost data. Dated pricing tables and real usage records are required before financial totals appear.", cards: [["Requests","Recorded after provider completion","READY FOR DATA"],["Estimated cost","Unavailable until pricing is configured","NOT CONFIGURED"],["Budget controls","Daily, monthly, and per-task gates","PLANNED"]] },
  integrations: { eyebrow: "SECURE CONNECTIONS", title: "Integrations", description: "Provider credentials are read server-side from environment variables. Values are never displayed or stored in project records.", cards: [["OpenAI","Requires OPENAI_API_KEY","SERVER ENV"],["Anthropic Claude","Requires ANTHROPIC_API_KEY","SERVER ENV"],["Future providers","Official APIs, SDKs, OAuth, or brokers only","ROADMAP"]] },
  approvals: { eyebrow: "HUMAN CONTROL", title: "Approval Center", description: "Consequential external actions remain blocked until a human approves their exact scope.", cards: [["External changes","Publishing, email, deployment, systems","REQUIRES APPROVAL"],["Sensitive access","Files, sharing, credentials","REQUIRES APPROVAL"],["Agent execution","Shell, code changes, commits","REQUIRES APPROVAL"]] },
  settings: { eyebrow: "PRIVATE WORKSPACE", title: "Settings", description: "Authentication, session, retention, provider, budget, and privacy controls for a production deployment.", cards: [["Authentication","Auth-ready; required before public exposure","ACTION REQUIRED"],["Secret vault","Use environment locally, managed vault in production","SECURE BOUNDARY"],["Emergency stop","Cancel new provider and agent work","PLANNED"]] }
};

export function PhasePage({ kind }: { kind: keyof typeof content }) { const page = content[kind]; return <AppShell><div className="page-wrap"><header className="page-head"><span className="eyebrow">{page.eyebrow}</span><h1>{page.title}</h1><p>{page.description}</p></header><div className="cards">{page.cards.map(([title,body,tag], i) => <article className="info-card" key={title}>{i === 0 ? <Sparkles size={18}/> : i === 1 ? <Network size={18}/> : kind === "approvals" ? <ShieldCheck size={18}/> : <Workflow size={18}/>}<h3>{title}</h3><p>{body}</p><span className="tag">{tag}</span></article>)}</div><div className="info-card" style={{marginTop:13}}><AlertTriangle size={17}/><h3>Honest capability boundary</h3><p>This workspace is part of the production structure, but its later-phase operations are not yet connected. Direct, Council, mock streaming, server-side OpenAI/Anthropic adapters, and project persistence form the Phase 1 working slice.</p></div></div></AppShell>; }
